language: node_js
node_js:
- node

env:
  global:
  - PUBLIC_DNS="ec2.xxxxx.eu-west-1.compute.amazonaws.com"
  - APP_NAME="node-js-app"

before_install:
- openssl aes-256-cbc -K $encrypted_633962bc81e3_key -iv $encrypted_633962bc81e3_iv
  -in .ssh/aws_terraform.enc -out .ssh/aws_terraform -d

after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .ssh/aws_terraform
- ssh-add .ssh/aws_terraform
- ssh-keyscan ${dokku_host} >> ~/.ssh/known_hosts
- git remote add dokku dokku@${dokku_host}:node-js-app
- git push dokku master
