language: node_js
node_js:
 - "node"
before_install:
 - openssl aes-256-cbc -K $encrypted_633962bc81e3_key -iv $encrypted_633962bc81e3_iv -in .travis/aws_terraform.enc -out .travis/aws_terraform -d
after_success:
 - eval "$(ssh-agent -s)" 
 - chmod 600 .travis/aws_terraform
 - ssh-add .travis/aws_terraform
 - git remote add dokku DEPLOY_REPO_URI_GOES_HERE
 - git push dokku
