language: node_js
node_js:
- node
env:
  global:
  - GIT_USERNAME="Travis CI"
  - GIT_REPO="git@github.com:radudd/node-js-sample"
before_install:
- openssl aes-256-cbc -K $encrypted_cfaf2b433683_key -iv $encrypted_cfaf2b433683_iv
  -in aws.tar.enc -out aws.tar -d
- tar xvf aws.tar && mv -fv .aws ~/
before_deploy:
- curl -sSL https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
  -o terraform.zip
- sudo unzip terraform.zip -d /usr/bin/
- rm terraform.zip
- eval "$(ssh-agent -s)"
- ssh-add .ssh/aws_terraform
deploy:
- provider: script
  script: ./terraform/deploy_aws_host.sh
  skip_cleanup: true
  on:
    branch: master
after_deploy:
- cd terraform && export dokku_host=`terraform output public_dns`
- ssh-keyscan ${dokku_host} >> ~/.ssh/known_hosts
- git remote add dokku dokku@${dokku_host}:node-js-app
#- for i in `seq 1 10`; do (ssh -q ${dokku_host} -l dokku ssh-keys:list && git push dokku master && break) || echo "Cannot deploy to Dokku :( ... "; sleep 10; done
- until ssh -q ${dokku_host} -l dokku ssh-keys:list; do sleep 30; done; git push dokku master
