language: node_js
node_js:
- node
env:
  global:
  - APP_NAME="node-js-sample"
  - APP_PORT=5000
  - GIT_USERNAME="Travis CI"
  - GIT_REPO="git@github.com:radudd/node-js-sample"
before_install:
- openssl aes-256-cbc -K $encrypted_cfaf2b433683_key -iv $encrypted_cfaf2b433683_iv
  -in aws.tar.enc -out aws.tar -d
- tar xvf aws.tar && mv -fv .aws ~/
- eval "$(ssh-agent -s)"
- ssh-add .ssh/aws_terraform
deploy:
- provider: script
  script: ./terraform/deploy_aws.sh
  skip_cleanup: true
  on:
    branch: master
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
