language: node_js
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_633962bc81e3_key -iv $encrypted_633962bc81e3_iv
  -in aws.tar.enc -out aws.tar -d
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- tar xvf aws.tar
- openssl aes-256-cbc -K $encrypted_633962bc81e3_key -iv $encrypted_633962bc81e3_iv
  -in .travis/aws_terraform.enc -out .travis/aws_terraform -d
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/aws_terraform
- ssh-add .travis/aws_terraform
- export dokku_host=`aws ec2 describe-instances --region eu-west-1 --filters "Name=tag:App,Values=Dokku" --filters "Name=instance-state-name,Values=running" --query 'Reservations[*].Instances[*].[PublicDnsName]' --output text`
- ssh-keyscan ${dokku_host} >> ~/.ssh/known_hosts
- git remote add dokku dokku@${dokku_host}:node-js-app
- git push dokku master
